### ISSUE TITLE
Integrate Crosswalk for old android versions?

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#122]
- https://crosswalk-project.org/
- might help reduce testing and development costs for old platforms

**Comment by MathiasTim** [comment]
Maybe check this:
http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html

**Comment by gruppjo** [comment]
Just found this as well: http://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html
Seems like this can be achieved by adding the Crosswalk plugin - https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview
