### ISSUE TITLE
Cordova update strategy

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#13]
How can projects created with the generator be updated:
* update platforms within the projects `cordova platform update <platform>`? - https://cordova.apache.org/docs/en/3.5.0/guide_cli_index.md.html#The%20Command-Line%20Interface
* update project itself? `config.xml` etc...

**Comment by gruppjo** [comment]
related to #14

**Comment by MathiasTim** [comment]
I think cordova solved this by itself: https://cordova.apache.org/docs/en/5.1.1/guide_cli_index.md.html#updating-cordova-and-your-project
