### ISSUE TITLE
Generator can't finish job trying to add Android

### ISSUE THREAD

**Issue by marcelaulenbacher** [mwaylabs/generator-m#131]
Hello.

I stumbled upon a problem trying to create an iOS/Android project:

`? Choose all bower packages in addition to angular, ionic, angular-ui-router, cordova and ngCordova: angular-dynamic-locale#~0.1.17, angular-localForage#~0.2.10, angular-touch#~1.2.25, angular-translate#~2.4.0, angular-translate-loader-static-files#~2.4.0, angular-ui-bootstrap-bower#~0.11.0, fastclick#~1.0.3, restangular#~1.4.0
? Do you want to use the sass version of ionic's css? not (faster)
? Do you want to use components (bower & npm) we deem stable or the latest ones? stable (recommended)
? Select all platforms you want to support: iOS, Android
? Select all cordova plugins you want to install: Device - org.apache.cordova.device, Dialogs - org.apache.cordova.dialogs, Network - org.apache.cordova.network-information, Splashscreen - org.apache.cordova.splashscreen, Toast - https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git
Created cordova project
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.mydocumenta.app
	Name: MyDocumenta
	Android target: android-19
Copying template files...
Running: android update project --subprojects --path "platforms/android" --target android-19 --library "CordovaLib"
Resolved location of library project to: /Users/marcel/workspace/mydocumenta/test/platforms/android/CordovaLib
Updated and renamed default.properties to project.properties
Updated local.properties
No project name specified, using Activity name 'MyDocumenta'.
If you wish to change it, edit the first line of build.xml.
Added file platforms/android/build.xml
Added file platforms/android/proguard-project.txt
Updated project.properties
Updated local.properties
No project name specified, using project folder name 'CordovaLib'.
If you wish to change it, edit the first line of build.xml.
Added file platforms/android/CordovaLib/build.xml
Added file platforms/android/CordovaLib/proguard-project.txt

Project successfully created.
Added platforms: ios, android
**Couldn't finish generator:**
**CordovaError: Plugin doesn't support this project's cordova-android version. cordova-android: 3.5.1, failed version requirement: >=3.6.0**`

**My installed cordova-android version is 3.7.1**

Do you have an idea what may be going wrong here?

**Comment by gruppjo** [comment]
What's the output of running?
```shell
gulp --cordova 'platform ls'
```

**Comment by gruppjo** [comment]
I just tried this. This looks like a problem of the cordova version that was most up to date when the generator-m version 0.2.7 was release in combination with the new toast plugin version. For now you can create the project without the plugin and add it later
```shell
gulp --cordova 'plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git'
```
The next generator version will be using the newest cordova version and then this shouldn't be a problem anymore.
Is this workaround enough for now?

**Comment by marcelaulenbacher** [comment]
Worked! Thank you!
