### ISSUE TITLE
When selcting no codrova plugins generator does not run

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#138]
just wanted to test something and thought I don't need a plugin.
Turns out the generator allows this, but then it does not finish correctly.

![screen shot 2015-02-28 at 09 48 16](https://cloud.githubusercontent.com/assets/1793379/6425570/922f0ffa-bf2f-11e4-87fd-491135326c2f.png)

**Comment by gruppjo** [comment]
duplicate and already fixed #105
