### ISSUE TITLE
How to use modules

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#148]
scss/sass components:
Current problem is, that importing variables from e.g. the main module is not so easy.
(I'll provide a better description later)
My workaround at the moment is, including all scss files with a simple @import in the main.scss and keeping one single main.css include in the index.html

Questions are:
 - how to solve the importing variables problem?
 - or is the described workaround the way to go?

**Comment by MathiasTim** [comment]
Another queston is, where to put the module imports like ionic, ng-cordova, etc.
In each module (current solution) or globally in app.js

**Comment by MathiasTim** [comment]
I would also appreciate if we had an option for the yo m:module sub generator to only generate the folders and the module.js file and dont generate the other stuff, because often you just delete them and dont need it.

Something like

```
yo m:module --blank
```

**Comment by gruppjo** [comment]
Modules also causing troubles with new gulp-ruby-sass https://github.com/mwaylabs/generator-m/issues/193#issuecomment-103958359

**Comment by gruppjo** [comment]
related to #161 (modules use wrong naming)

**Comment by gruppjo** [comment]
Result of discussion:
- module: name start ctrl, template, service based on module name
- name config: `<moduleName>Config`, `Config`
- go with gulp sass
