### ISSUE TITLE
windows: gulp watch crashes when building

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#156]
1. run `gulp watch`
1. run `gulp build` in another cmd
1. gulp watch crashes with `Error: watch EPERM`

Occurs both on windows 7 & 8

**Comment by gruppjo** [comment]
Seems to be a common problem with windows:
- https://github.com/gulpjs/gulp/issues/738 (changing any globbing when deleting didn't help
- https://github.com/gulpjs/gulp/issues/660

**Comment by AbdulBasitBashir** [comment]
ok i'll try comment on this post it's work or not wait a while

**Comment by AbdulBasitBashir** [comment]
Sorry not working

**Comment by gruppjo** [comment]
Hi @AbdulBasitBashir. Thanks for trying this. I closed it because it's a problem with `del` or actually rather the windows file system and not the generator. So there's nothing we can really do about it...

**Comment by AbdulBasitBashir** [comment]
Thanks you so much
but i resolved it already....
again thanks you so much...






Regards : ABDUL BASIT

**Comment by gruppjo** [comment]
How did you do that? :)
It might be helpful for other users, if you post your solution here!

**Comment by AbdulBasitBashir** [comment]
i will post.






Regards : ABDUL BASIT

**Comment by AbdulBasitBashir** [comment]
code zip







Regards : ABDUL BASIT

On Mon, Sep 7, 2015 at 1:17 PM, Abdul.Basit Bashir <abdul.basit264@gmail.com

**Comment by jmartsch** [comment]
@AbdulBasitBashir Hi, your zip-file is not attached. Could you make a gist or post your solution as inline-code here? Thanks in advance.

**Comment by bhargavgunreddy** [comment]
Is this issue resolved ?
