### ISSUE TITLE
generator-m default is not working on Windows

### ISSUE THREAD

**Issue by crowne** [mwaylabs/generator-m#160]
Hi,

I followed the instructions to get started, but I cannot get a basic sample running on Windows 7.
Node is running in MINGW32.

There were some errors reported after yo-m.
npm WARN optional dep failed, continuing imagemin-pngquant@4.0.0
npm ERR! Error: EPERM, open 'C:\Users\crowne\AppData\Roaming\npm-cache\b21bf682-cache-inherits-2-0-1-package-tgz.lock'

I reran npm install and got Error: Cannot find module 'readable-stream'
gulp watch gives Error: Cannot find module 'wiredep'

What can I do to resolve these errors?

Regards,
Neil

**Comment by gruppjo** [comment]
Hi Neil,
running the generator on windows usually isn't a problem. What you could do is:

- delete the `node_modules` folder in the generated project and rerun `npm install`

if that doesn't work:
- install node.js for windows https://nodejs.org/download/, without MINGW32. 

That's how we successfully run generator-m on windows.

Please let us know whether this was of any help!

**Comment by crowne** [comment]
Thanks Jonathon.
I had to upgrade npm from 1.4.28 to latest (2.7.5).
I had to npm clean cache.
I had to reboot windows, after clean cache to eventually get an install working.
But I now have the scaffold running.
