### ISSUE TITLE
module use wrong naming

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#161]
example create a module 
`````
yo m:module foo-bar
``````
creates a folder foo-bar the problem when is use a subgenerator in get something like 
``````
angular.module('foo-bar') 
`````
but the generated Name is fooBar

**Comment by gruppjo** [comment]
I'm not sure whether I fully understood what you are trying to do, but:
As indicated by the README.md moduleNames should always use camelCase notation
see: https://github.com/mwaylabs/generator-m#sub-generators

**Comment by MathiasTim** [comment]
Just a quick thought I saw when reading the sub-generators part in readme:
Is there a reason why you write: 
> navigate to http://127.0.0.1:9000/#/<module-name-in-snake-case> in your browser.
because in other cases you write
> navigate to http://localhost:9000 yourself

would be good if this is written the same if it makes no difference

**Comment by DrMabuse23** [comment]
So the problem is i can only name my Folders fooBar not foo-bar 
because yo m:service fooService fooBar creates not a service in folder foo-bar only in folder fooBar

**Comment by gruppjo** [comment]
related to #148 (how modules work)

**Comment by gruppjo** [comment]
as discussed, use camelCase Notation
