### ISSUE TITLE
Double injects bower files

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#162]
I installed bikini in client and the inject add
`````
<script src="bower_components/bikini/dist/bikini.js"></script>
<script src="bower_components/bikini/dist/bikini.min.js"></script>
``````

**Comment by MathiasTim** [comment]
As far as I know, this has to be maintained by the owner of the soruce repo.
All files added to the 'main' attribute in the bower.json will be included by the gulp-inject

so I think you have to change this here:
https://github.com/mwaylabs/bikini/blob/master/bower.json#L5

**Comment by DrMabuse23** [comment]
Yes
