### ISSUE TITLE
create cordova hooks

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#171]
To solve some problems like manipulation the plist, we need to use cordova hooks.

We should write a colletion of most used cordova hooks and maybe integrate them then into generator-m.

**Comment by stefanjauker** [comment]
why would you manipulate the plist file?

**Comment by MathiasTim** [comment]
For example to add the supported languages on iOS to the app. In this way labels on buttons from native plugins will be translated.
i.e.: the camera plugin will always display 'use photo' although your are on a device that has german as language. That can be solved if you add the 'supported languages' to the app. Then iOS will translate system labels in the correct language.

**Comment by MathiasTim** [comment]
I talked to Frank today, he used this hook, for my described usecase above:

https://github.com/djett41/generator-ionic/blob/master/templates/hooks/after_prepare/update_platform_config.js

I like it, and think we should think about a way to scaffold this with the generator-m (at least ask the user)

**Comment by FrankStierle** [comment]
This Hook can also add all kind of entries to the AndroidManifest.xml if specified in the config.xml.

Very useful

**Comment by gruppjo** [comment]
Maybe we can provide an `m:hook` subgenerator.

related #184, #183

**Comment by gruppjo** [comment]
#188 (add badges on app icons)

**Comment by gruppjo** [comment]
Cordova hooks docs - http://cordova.apache.org/docs/en/edge/guide_appdev_hooks_index.md.html#Hooks%20Guide

**Comment by gruppjo** [comment]
Discussion:

- include the following hook: https://github.com/diegonetto/generator-ionic/blob/master/templates/hooks/after_prepare/update_platform_config.js
  - include the following packages as devDependencies in the `package.json` https://github.com/diegonetto/generator-ionic/blob/master/templates/hooks/after_prepare/update_platform_config.js#L80-L82
  - include for android and ios with the `config.xml` syntax - http://cordova.apache.org/docs/en/edge/guide_appdev_hooks_index.md.html#Hooks%

Nice to have in the future: provide hooks as node module.

**Comment by gruppjo** [comment]
Adding 
```xml
  <platform name="android">
    <hook type="after_prepare" src="hooks/update_platform_config.js"/>
  </platform>
  <platform name="ios">
    <hook type="after_prepare" src="hooks/update_platform_config.js"/>
  </platform>
```
to the `config.xml` results in the following error when running `gulp --cordova 'run ios'`
```
ERROR running one or more of the platforms: TypeError: invalid data
You may not have the required environment or OS to run this project
```

**Comment by gruppjo** [comment]
closed with https://github.com/mwaylabs/generator-m/commit/9a36328a7624e6104be26793f3fec9b16e9d005e

**Comment by MathiasTim** [comment]
I thought we will not support the [deprecated](https://github.com/mwaylabs/generator-m-demo/tree/master/hooks#cordova-hooks) method with using the ```hooks``` folder for cordova hooks?

Although the [demo](https://github.com/mwaylabs/generator-m-demo) has it. Is there any reason why?

**Comment by gruppjo** [comment]
Yes! See the comment above. https://github.com/mwaylabs/generator-m/issues/171#issuecomment-133496975
Feel free to try this and let me know if you get the same error, when using the `config.xml` method.
