### ISSUE TITLE
Nested Objects in Environment

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#172]
Hi i try using nested Objects in env for debugging like this 
````
{"TANGA": {
    "DEBUG": {
      "WEBSOCKET": true,
      "COLLECTION": true,
      "STORE": true
    }
  }
}
`````
Problem is jshint failed on Build.

**Comment by gruppjo** [comment]
Hi,
you're right. It never occurred to me but this is an obvious use case. I fixed this. If you want to fix it in your gulp task. Replace the following line: https://github.com/mwaylabs/generator-m/blob/63a2b2a9be9dd35a93247ab0a48cfc04a91c31a1/app/templates/gulp_tasks/injecting.js#L92
```js
json = json.replace(/  /g, '');
```
with this:
```js
json = json.replace(/^  /g, '');
```

**Comment by DrMabuse23** [comment]
Nice thanks
