### ISSUE TITLE
wrong controller instantiation with multiple modules

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#173]
1. `yo m --skip-prompts`
1. `gulp watch`

StartCtrl and Service from module main are properly instantiated 

1. `yo m:module test`
1. `gulp watch`
1. go to `http://127.0.0.1:9000/#/main`

StartCtrl and Service from module test instead of main are falsely instantiated

This seems to be a general problem with angular since the problem occurred without using ui-router as well and even without controllerAs syntax. However I'm fairly sure this worked correctly in earlier versions.
index.html:
```html
<ion-nav-view>
  <ion-view view-title="main module" ng-controller="StartCtrl as start">
    <ion-content>
      <ion-list>
        <ion-item class="item item-divider">
          This is your start template!
        </ion-item>
        <ion-item class="item item-icon">
          icons working?
          <i class="icon ion-checkmark-circled"></i>
        </ion-item>
        <ion-item class="item item-thumbnail">
          images working?<br>
          <img width="75" src="main/assets/images/yo@2x.png">
        </ion-item>

        <ion-item class="item">{{start.someData.binding}}</ion-item>
        <ion-item class="item item-divider">Environment variables:</ion-item>
        <ion-item class="item item-text-wrap">
          <pre>{{start.ENV | json}}</pre>
        </ion-item>
        <ion-item class="item item-divider">Build variables:</ion-item>
        <ion-item class="item item-text-wrap">
          <pre>{{start.BUILD | json}}</pre>
        </ion-item>

      </ion-list>
    </ion-content>
  </ion-view>
</ion-nav-view>
```

main.js
```js
'use strict';
angular.module('main', [
  'ionic',
  'ngCordova',
  'ui.router',
  // TODO: load other modules selected during generation
]);
// .config(function ($stateProvider, $urlRouterProvider) {

//   console.log('Allo! Allo from your module: ' + 'main');

//   $urlRouterProvider.otherwise('/main');

//   // some basic routing
//   $stateProvider
//     .state('main', {
//       url: '/main',
//       templateUrl: 'main/templates/start.html',
//       controller: 'StartCtrl as start'
//     });
//   // TODO: do your thing
// });
```

**Comment by MathiasTim** [comment]
Just checked this out. Same for me here.

But i'm not so sure about the point, that this worked in earlier versions.
I just saw, that it depends, how you 'inject' the modules into each other.

```javascript
angular.module('myProject', [
  // your modules
  'test',
  'main'
]);
```
Seems like last one 'wins'.

Apart from this problem, I would prefer a naming of the start controller, service etc in the module name.
This seems far more useful, than 'start' to me.

**Comment by gruppjo** [comment]
I'll look into it. Thanks for verifying :+1:

**Comment by gruppjo** [comment]
Found this: http://stackoverflow.com/questions/13406791/modules-and-name-clashes-in-angularjs/19820088#19820088
In my opinion that's a strong reason **against** using modules in Angular 1.x. Angular 2 won't have this problem due to ES6 modules, since the application programmer is able to manage the naming of the imports her/himself: https://github.com/lukehoban/es6features#modules

**Comment by gruppjo** [comment]
related to #148 and #161

**Comment by gruppjo** [comment]
@MathiasTim I think naming the start controller, services templates and config constant based on the module name is a good idea. Unfortunately this is quite a bit of work and it also affects how the config constant and its gulp tasks should work. Let's discuss this.

**Comment by MathiasTim** [comment]
related to: #148

@gruppjo @DrMabuse23 I think we should set up a meeting via Skype, or maybe at M-Way to discuss this. Im not really convinced by our current strategy/use of modules in angular.

**Comment by gruppjo** [comment]
Result of discussion:
- module: name start ctrl, template, service based on module name
- name config: <moduleName>Config, Config

**Comment by LunarDevelopment** [comment]
I may be being stupid here, but does this address the issue that each module is created via the  `yo m:module <modName>` command ends up with the view and controllers called 'start' 

Which I had to manually rename as my abstract view controller with its default StartCtrl name didnt work as it was clashing with the other module (main)'s controller named StartCtrl

**Comment by gruppjo** [comment]
Hi @LunarDevelopment. That exactly is the problem.
