### ISSUE TITLE
Provide dedicated folder for cordova assets

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#18]
Provide a dedicated folder for cordova assets that are copied to the right location when building
* splash screen
* app icons

**Comment by MathiasTim** [comment]
Im not sure what do you want to approach, with this issue.
Is it just to make a folder in the project root?

Right know I do it like that
- resources
-- ios
-- android

**Comment by anasmithiam** [comment]
I agree with @MathiasTim's proposal. Is the same approach followed by ionic-cli projects (and also it may be the "standard way" to deal with platform resources in cordova projects).

I think the best approach would be the nearest with the applied one in the ionic-cli projects.

**Comment by LunarDevelopment** [comment]
Would it be possible to have a short explaination or an update of the readme to explain to a novice hot to add a splash screen etc to a project?

I've done this through phonegap before, however never through ionic and never through generator-m, making me skittish as to how to go about it without ruining my app in some way.

Sorry to be so needy!

**Comment by gruppjo** [comment]
Hi @LunarDevelopment, right now you can simply add splash screens (and app icons) to your project as intended by cordova. Check out the documentation: http://cordova.apache.org/docs/en/5.1.1/config_ref_images.md.html#Icons%20and%20Splash%20Screens

This issue, and #188 are thoughts on how to extend and further simplify the functionality that is already available in cordova.

**Comment by LunarDevelopment** [comment]
Both great things to know, thank you very much for your time! 

:+1:

**Comment by MathiasTim** [comment]
We will add something like this with #188 and #171

**Comment by gruppjo** [comment]
closed with https://github.com/mwaylabs/generator-m/issues/171
