### ISSUE TITLE
Set android:versionCode in config.xml for AndroidManifest.xml

### ISSUE THREAD

**Issue by jonaskaufmann** [mwaylabs/generator-m#183]
The setBuild command should also set the Android VersionCode in the config.xml

Example:
gulp config --setBuild=${BUILD_NUMBER}

Generated AndroidManifest.xml:
android:versionCode="1" android:versionName="2.0.0.3"

**Comment by gruppjo** [comment]
modify `gulp config` to accept `--setAndroidVersionCode=123` option. @MathiasTim will provide a screenshot with the resulting `config.xml`.

**Comment by MathiasTim** [comment]
```id="com.mway.test" android-versionCode="0"```
