### ISSUE TITLE
Provide feature to sign android apps

### ISSUE THREAD

**Issue by jonaskaufmann** [mwaylabs/generator-m#184]
The gulp:build command should provide the possibility to sign Android apps

Example Jenkins config:
gulp --cordova 'build --release android'
jarsigner -verbose -keystore ${WORKSPACE}/keystore/app.keystore -storepass 'xxx' ${WORKSPACE}/platforms/android/ant-build/MainActivity-release-unsigned.apk xxAliasxx
zipalign -v 4 ${WORKSPACE}/platforms/android/ant-build/MainActivity-release-unsigned.apk ${WORKSPACE}/platforms/android/ant-build/AppName-release-signed.apk

**Comment by gruppjo** [comment]
@MathiasTim and I think this is better done using Jenkins since it's necessary to call command line tools which are not provided by node.
