### ISSUE TITLE
Disable zoom on input focus (Android)

### ISSUE THREAD

**Issue by lordgreg** [mwaylabs/generator-m#185]
Steps to reproduce:
1. Generate new project with `yo m`
2. Create template `yo m:template test` and add an input field to it. Example:
`<input type="search" name="search" ng-model="start.someData.searchString" ng-minlength="3" placeholder="Search">`
3. Test new template on Android emulator or Android device. I've used the phone (Sony Xperia Z with Lollipop AOSP). Pressing on input field automatically zooms on focused input. You cannot manually zoom out afterwards either.

![screenshot_2015-05-08-12-01-43](https://cloud.githubusercontent.com/assets/480546/7534479/32e473a0-f57b-11e4-9752-90fa6f3a7043.png)
4. Replacing part of `index.html` (generated by generator-m) has fixed this issue for me:
Before:
`<meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">`

After:
`<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />`
5. Result:
![screenshot_2015-05-08-12-04-59-1](https://cloud.githubusercontent.com/assets/480546/7534485/4088e00e-f57b-11e4-84d8-19234f142a3a.png)

**Comment by gruppjo** [comment]
Hi, thank you for creating this issue :+1:  We'll try to verify and then we'll discuss!

**Comment by MathiasTim** [comment]
I'm confused this issue didn't occur on any projects I did. Maybe this device has a special browser version?!

**Comment by MathiasTim** [comment]
I had the same issue today and the described fix does word. Although I don't think we need the 'height=device-height' part.
My changes are:
```
-    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
+    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no, minimal-ui" />
```

**Comment by gruppjo** [comment]
The ionic docs suggest it like this:
```html
<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
```
I guess missing ingredient is the `maximum-scale=1`.
Since I can't think of any reason why we should do it differently I'm gonna include the viewport meta description from the ionic documentation. Ok?
