### ISSUE TITLE
Improved linting (javascript)

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#186]
- https://github.com/angular/angular-hint
- improve, extend our current jscs/jshint
- consider another linter: https://github.com/eslint/eslint (instead of jshint AND jscs)
- check how many or if console.log, etc. are in the code ??

**Comment by gruppjo** [comment]
ESlinting looks nice: http://elijahmanor.com/talks/js-smells/

**Comment by RolandJansen** [comment]
Would be nice to exclude comments from getting linted. This is somewhat confusing.
![screen shot 2015-06-16 at 07 47 46](https://cloud.githubusercontent.com/assets/12171302/8176797/47533f32-13fe-11e5-85f4-44c6a0a697d3.png)
![screen shot 2015-06-16 at 07 48 01](https://cloud.githubusercontent.com/assets/12171302/8176799/4a2a7464-13fe-11e5-94b9-f7d063b0745e.png)

**Comment by gruppjo** [comment]
Hi @RolandJansen can you please create a new issue for that? jscs should never check comments. It might be a problem with your installed jscs version. What does running `jscs -V` in the terminal yield?

**Comment by gruppjo** [comment]
tslint https://www.npmjs.com/package/tslint

**Comment by MathiasTim** [comment]
We should also think about what jshint globals are added to the project by default:
now:
```"globals": {
    "angular": false
}```
my proposal:
```"globals": {
    "angular": false,
    "ionic": false
}```

you can use ```[ionic.Platform](http://ionicframework.com/docs/api/utility/ionic.Platform/)``` to determine on which platform (ios/android/etc.) you are.

**Comment by gruppjo** [comment]
I'm heavily in favour of **eslint**:
- easy to configure for ES6, different parsers, ... http://eslint.org/docs/user-guide/configuring
  - very extensive list of rules - http://eslint.org/docs/rules/
  - it's easy to configure environments - http://eslint.org/docs/user-guide/configuring.html#specifying-environments
  - if environments don't suffice you can define your own globals - http://eslint.org/docs/user-guide/configuring.html#specifying-globals
  - extend other configuration files - http://eslint.org/docs/user-guide/configuring.html#extending-configuration-files
- provides rules just as you wanted @MathiasTim.
  - a rule to check for **console** 
  - we can get rid of the `.jshintignore`
- it's faster than jscs (although probably nobody will notice)
- already has more downloads than jscs 
  - https://www.npmjs.com/package/jscs
  - https://www.npmjs.com/package/eslint
- has pluggable rules (write your own)
- already existing rules for angular via plugin https://github.com/Gillespie59/angularjs-eslint
- the gulp plugin looks neat and could resolve some of the issue we have with the other plugins - https://www.npmjs.com/package/gulp-eslint
- it can map **all of the rules we have in jshint and jscs** and more (no overlaps anymore, and I think the rules are a little more tactile, precise and less verbose)
  ```
  // JSCS equivalents
indent
curly
no-trailing-spaces
no-mixed-spaces-and-tabs
no-multi-str
space-after-keybowrd
space-before-blocks
space-before-function-paren
space-infix-ops
key-spacing
eol-last
no-unexpected multiline
operator-linebreak
no-multiple-empty-lines

// USEFUL
no-irregular-whitespace
linebreak-style
no-debugger
no-console
comma-spacing

// JSHINT equivalents
eqeqeq
wrap-iife
no-use-before-define
no-unused-vars
no-undef
no-caller
camelcase
no-bitwise
strict
quotes
new-cap
globals (angular, ionic)
```

I'll implement and test this and report back with findings.

**Comment by MathiasTim** [comment]
great! Im looking forward to this :)

**Comment by gruppjo** [comment]
Webstorm https://github.com/mwaylabs/generator-m/commit/b4897418acf29472ea83a750e8fe11370c4ed5d6#commitcomment-13081877
