### ISSUE TITLE
change icons and splash screens in build step

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#188]
I just ran into the problem, that I had two versions of the app on my phone and didn't know which one was the dev or prod.
Before we used cordova we had this badges on the app icons. Maybe we can find a method to add these badges again.

**Comment by gruppjo** [comment]
`resources/` folder with different app badge icons (prod, dev, beta, ...)

**Comment by gruppjo** [comment]
maybe this - https://github.com/djett41/generator-ionic/blob/master/templates/hooks/after_prepare/icons_and_splashscreens.js

**Comment by gruppjo** [comment]
cordova doc for icons and splashscreens - http://cordova.apache.org/docs/en/5.1.1/config_ref_images.md.html#Icons%20and%20Splash%20Screens

**Comment by MathiasTim** [comment]
so, I have no problem to take the name from cordova and name the folder 'res', anyone else?

**Comment by gruppjo** [comment]
closed with https://github.com/mwaylabs/generator-m/issues/171
