### ISSUE TITLE
Building Bug when install Snap.svg

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#196]
Hi ,
i install Snap.svg over bower. When i use "gulp build" the build task install the package into main/assets/fonts and get an allocated heap size.
Would be nice this can be express fixed,
thx a lot

**Comment by DrMabuse23** [comment]
quick solutoin var fontFiles = mainBowerFiles({filter: /\.(eot|svg|ttf|woff)$/i}) add the $ to the regexp

**Comment by gruppjo** [comment]
Took me a while to figure what you meant. The fix is upstream now. Thank you!
