### ISSUE TITLE
different module templates

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#198]
- implement extended example code like in ionic cli (side menu, tab nav) - https://github.com/driftyco/ionic-cli#starting-an-ionic-app
- standard modules
- blank modules (e.g. --blank)

**Comment by anasmithiam** [comment]
I think this is an important issue to attract more people to use this generator. it would be easier to people not accustomed to organize the code into feature-modules if the generated code shows how get an ionic app with tabs or sidemenus and more than one feature-module.

related #157

**Comment by ismusidhu** [comment]
+1 
I had to saperately generate ionic app and then pick code bits from there.

**Comment by LunarDevelopment** [comment]
:+1: Desperatley, I'm getting a bit lost now that I've made 'navigation', 'main' and 'about' modules.

Of course through research I'm aware I should have some kind of 'common' module fore nav bar etc but its still a case of working blind for someone new to this generator and using more than one module in a project.

**Comment by gruppjo** [comment]
Hi @LunarDevelopment! When you're a beginner I'd recommend you only use one module for everything. We only use modules for very large projects. That makes it easier at the beginning and you don't have to worry about what you is best put where which lets you stay focused on what's important! :)

**Comment by LunarDevelopment** [comment]
Solid advice that I'll take, Thankyou very much!

Lewis

**Comment by gruppjo** [comment]
I created an repository with the templates like we're going to implement them. Feedback welcome!
https://github.com/gruppjo/generator-m-templates

**usage**
- run `yo:m` (for a new project) or type `yo m:myModule` (for a new module)
- choose between: sidemenu, tabs and blank template

**Comment by gruppjo** [comment]
The implementation is in the master. Feedback still welcome!

**Comment by LunarDevelopment** [comment]
I'm running latest generator-m and I'm not getting this, 

I run `yo m:module test sidemenu`

and I get a standard module with no additional views or states beyond start.html etc.

**Comment by gruppjo** [comment]
That's because it hasn't been released yet. If you want to work with the most current (but unstable) version of the generator that includes this feature, you need to clone this repository and `npm link` it.

**Comment by LunarDevelopment** [comment]
Aha, that explains it. 

Thank you for the fast response! 

Lewis

**Comment by ronak-gitome** [comment]
Can anyone help me!
Just wanted to know...how to use same template from one module to another?
For Ex. - I created one module with side menu, now I want to create another module -blank, because menu is already in one module..So, now how to use that menu as common for the rest of modules I will create.
