### ISSUE TITLE
bower_components not minified when minify flag is on

### ISSUE THREAD

**Issue by Sturgelose** [mwaylabs/generator-m#206]
If you choose -minify, the cordova plugins won't be minified. You can see cordova.js without being minified neither any of the its plugins.

Only app.js, vendor.js and the styles will be uglified.

Using command `gulp --cordova "run android" --env=prod --minify` on generator-m version 1.1.0

**Comment by Sturgelose** [comment]
Okay, figured out that it seems that is the actual default behavior of Cordova. Sorry for the silly issue!

**Comment by gruppjo** [comment]
Hi @Sturgelose. No worries. Actually I've never though about that, so thank you for pointing it out :) But in fact that's something cordova would need to be configured to do. Do you know whether cordova is capable of doing so?

**Comment by Sturgelose** [comment]
Hi @gruppjo, I did some research yesterday late night, and I wasn't able to change any setting in cordova to do so. The thing is that if you check in the plugin folder of the project, you will find a minified version, so it this points it should be away to use minified versions of the js somehow...

**Comment by MathiasTim** [comment]
hey, just a thought:

This could maybe achived bt using [cordova hooks] (http://cordova.apache.org/docs/en/edge/guide_appdev_hooks_index.md.html#Hooks%20Guide)

**Comment by gruppjo** [comment]
Good idea. Cordova hooks #171
