### ISSUE TITLE
Cant compile anymore Sass Files

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#209]
My Node Sass version: 
`````
node-sass -v
node-sass       3.2.0   (Wrapper)       [JavaScript]
libsass         3.2.5   (Sass Compiler) [C/C++]
``````
Try to reinstall but nothing changed:
`````
Error: `libsass` bindings not found in /client/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath /client/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous>/client/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/client/node_modules/gulp-sass/index.js:163:21)
    at Module._compile (module.js:460:26)
`````

Node Version:

`````
node -v
v0.12.6
``````

**Comment by ebarbeito** [comment]
Some weeks ago I came up with this issue. I solved it running manually this:

```
$ cd node_modules/gulp-sass/
$ node ./node_modules/node-sass/scripts/install.js
```

This should fix it. Try again the task you have run before.

**Comment by gruppjo** [comment]
@ebarbeito which version of node are you running? Also 0.12.6 just like @DrMabuse23?
Everything seems to run fine on my machine:
`$ node -v
v0.12.5
`

**Comment by ebarbeito** [comment]
@gruppjo I got this error with node v0.12.4 in a vagrant/virtualbox environment.

I just tested `npm install` in the same project without `node_modules/` dir and now it works fine. Using the same environment and node version.

Sorry but I can't reproduce the issue again.

**Comment by gruppjo** [comment]
@ebarbeito thanks for clarifying and sharing your fix!

@DrMabuse23 does deleting the `node_modules/` folder and running `npm install` again fix this issue for you as well?

**Comment by ebarbeito** [comment]
You are welcome @gruppjo! Just tell me if more tests are needed and thanks to you for this great generator

**Comment by gruppjo** [comment]
@ebarbeito, glad you feel that way :)
