### ISSUE TITLE
gulp watch-build not working anymore

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#210]
To fix in your project without waiting for the next release, replace this line:

`gulp_tasks/watching.js` line 85
```js
gulp.task('connect-build', createConnectServer(paths.dist));
```

with this
```js
gulp.task('connect-build', createConnectServer([paths.dist]));
```

**Comment by anasmithiam** [comment]
Fixed in my project :+1: 
This will be committed in master? Thanks!

**Comment by gruppjo** [comment]
Yes, very soon!
