### ISSUE TITLE
choose pre-compiled version of ionic css

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#212]
Introduce an option for the user when setting up the project that provides the user either with a precompiled version of the ionic css or one that is compiled with every `styles` gulp task (as it is now).

This could greatly reduce the sass compile time for many use-cases. See https://github.com/mwaylabs/generator-m/issues/3#issuecomment-122716113

**Comment by MathiasTim** [comment]
I just tried out this feature, its cool. But there is something which bothers me.
Why is the 'css-way' recommended? I cannot agree there. Of course its faster, but you loose the ability to change any color/variable of ionic and we do this a lot!
<img width="687" alt="screen shot 2015-09-05 at 13 53 30" src="https://cloud.githubusercontent.com/assets/1793379/9699116/ef94d9f0-53d5-11e5-94a5-4cebb6aea51b.png">

So I think we should do this:
```
❯ ionic SASS (more flexible)
 ionic CSS (faster) 
```

**Comment by gruppjo** [comment]
I thought that most people would probably use ionic 'as is'. What do you think? However I'm totally open to changing it.

**Comment by gruppjo** [comment]
change:
```
> ionic CSS (faster, for beginners)
ionic SASS (more flexible, for pros)
```
