### ISSUE TITLE
get/set version of project with jenkins

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#214]
- TBD
- Discussion

**Comment by gruppjo** [comment]
`gulp config --getVersion`

**Comment by MathiasTim** [comment]
Maybe this is more related to #183 as we thought.

Because jenkins has to manipulate the ```android-versionCode``` right now.
With this method we can only get the version=""

**Comment by MathiasTim** [comment]
Maybe this is more related to #183 as we thought.

Because jenkins has to manipulate the ```android-versionCode``` right now.
With this method we can only get the ```version="0.0.1"```

**Comment by gruppjo** [comment]
@MathiasTim, I was having some thoughts about this issue and I took the liberty to revamp the `gulp config` task. I think it's much more flexible now and you'll be able to perform all the necessary tasks easily. 

All documented here: https://github.com/mwaylabs/generator-m/blob/master/docs/guides/programmatically_change_configxml.md

Feedback please :)

**Comment by gruppjo** [comment]
@MathiasTim, I was having some thoughts about this issue and I took the liberty to revamp the `gulp config` task. I think it's much more flexible now and you'll be able to perform all the necessary tasks easily. 

All documented here: https://github.com/mwaylabs/generator-m/blob/master/docs/guides/programmatically_change_configxml.md

Feedback please :)
