### ISSUE TITLE
scss module.scss

### ISSUE THREAD

**Issue by DrMabuse23** [mwaylabs/generator-m#217]
yo m:module generate a ```module.scss``` not a ```_module.scss```
Problem no variables are longer available!!!

**Comment by gruppjo** [comment]
Hi @DrMabuse23, can you please specify, what variables are you talking about, what is the use-case exactly?
Unless you're using sass in a way that I don't have in my mind right now, I don't see the problem. It's always been like this and the new modules and the scss integration have been implemented in the way we all discussed and agreed on. See https://github.com/mwaylabs/generator-m/issues/148

**Comment by DrMabuse23** [comment]
I`am talking about the ionic variable and we discussed in the meeting that we want => module network => styles/_network.scss.

**Comment by gruppjo** [comment]
For the last release we agreed on these changes. https://github.com/mwaylabs/generator-m/issues/148#issuecomment-112021578
We'll discuss this feature and put it on the roadmap accordingly

**Comment by gruppjo** [comment]
Discussion:

Mathias:
- naming: `module.scss` rather `main.scss`, `side.scss`, etc...

Jonathan:
- don't destroy newbie workflow:
  1. create module
  2. make css adjustments
  3. see live with livereload
- don't create unnecessary complicated logic, try to find a solution that fits all
