### ISSUE TITLE
Enhance index.html template

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m#218]
I think there are some meta-tags, etc. that could enhance and simplify the experience

e.g.: 
- ```<meta name="format-detection" content="telephone=no">``` we use this in every app (ios)
- ```<meta name="apple-mobile-web-app-capable" content="yes">``` when also used in browsers

[here are some examples for ios](https://developer.apple.com/library/safari/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html)

maybe we can summarize a few enhancements and then integrate them into the project

**Comment by gruppjo** [comment]
:+1:

**Comment by MathiasTim** [comment]
I think we should add the two lines above in the 1.3.0. But keep the ticket open, if we find more useful stuff. @gruppjo ok for you?

**Comment by gruppjo** [comment]
:+1:
