### ISSUE TITLE
Controller generation breaks watch/building tasks because of "Indentation"

### ISSUE THREAD

**Issue by Telemakhos** [mwaylabs/generator-m#221]
Is this project being developed in Windows machines? I'm not sure why but generating a controller with the default install will break the app. For instance I generate a controller named login (just as an example) and then:

```
Error in plugin 'gulp-jscs'
Message:
    Expected indentation of 2 characters at main/controllers/login-ctrl.js :
     2 |angular.module('main')
     3 |.controller('LoginCtrl', function () {
     4 | console.log('Hello from your Controller: LoginCtrl in module main:. This is your controller:', this);
----------^
     5 | // TODO: do your controller thing
     6 |});

```

I decided to delete the jscs task from the build and I can work with it, but the defaults in this project need some double-checking...

cheers

**Comment by gruppjo** [comment]
Hi @Telemakhos, we're working on Mac OS X just like you.
This is very odd. 

- Do you have the latest version of the generator installed?
- Can you provide a minimal use case which result in the described behaviour?
  - Include the commands you use.
  - Include the output just as I did above.

When I run `yo m:controller Login` this is the result:
```js
'use strict';
angular.module('main')
.controller('LoginCtrl', function () {

  console.log('Hello from your Controller: LoginCtrl in module main:. This is your controller:', this);
  // TODO: do your controller thing

});
```
which passes the jshint checks just fine, with proper indentation and all.

We're using yeoman's templating engine whose syntax you can look at here: http://ejs.co/. In the case of a component creation (like a controller). The sub-generator will just template the original file with the passed in parameters.
The controller template file is located here: https://github.com/mwaylabs/generator-m/blob/master/controller/templates/_controller.js

As you can see there's not much that can go wrong with indentation in this process (regardless of the OS). It confuses me a little how you got this error though...
