### ISSUE TITLE
Coffeescript integration

### ISSUE THREAD

**Issue by LunarDevelopment** [mwaylabs/generator-m#222]
Ola! 

Are there any plans on integrating `--coffee` option into this generator, similar to generator-angular ?

Lewis

**Comment by gruppjo** [comment]
Hi @LunarDevelopment, unfortunately no. Sorry. There might be in the future, but for now, not at all. But even then, in the farther away future, the next big changes will be ES6 Syntax and possibly Angular 2.0.

**Comment by LunarDevelopment** [comment]
Cool, Thanks for the info!
