### ISSUE TITLE
browsersync instead of livereload

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#228]
Browsersync may be better in a couple of cases for us:

- automatically uses a free livereload and browser port (livereload requires hard-coded values)
  - thus: several watch tasks (of different projects) could run at the same time
  - also: gulp watch could be run alongside other tasks that use gulp serve (e.g. gulp protractor etc...)
  - also: gulp protractor could be terminated by calling `browserSync.exit()`
- it prints the url with the port for the user

**Comment by gruppjo** [comment]
Some more tweaks will be necessary to get all of the above features to run.

**Comment by MathiasTim** [comment]
I'm not sure, but shouldn't it be possible with browsersync, that you can run multiple projects with out getting: ```EADDRINUSE``` ?

I tried it with the demo repo and got this:
<img width="608" alt="screen shot 2015-09-05 at 13 23 14" src="https://cloud.githubusercontent.com/assets/1793379/9699020/8ffc65a2-53d1-11e5-94a4-6d956f903e3a.png">

With protractor everything is fine (operates on different ports I assume?!).
