### ISSUE TITLE
Test tasks are missing

### ISSUE THREAD

**Issue by drissamri** [mwaylabs/generator-m#233]
The documentation mentions gulp karma and gulp protractor should work, but in generator 1.2.2 no test tasks are generated?

**Comment by MathiasTim** [comment]
Hey, the documentation refers to the current master. The 1.2.2, which is the latest release did not have this feature: https://github.com/mwaylabs/generator-m/tree/1.2.2

We will release a new version with test integration soon.
So we are sorry for the confusion, but you will have to wait a little bit more.

Or check our the master and do ```npm link``` inside the directory. In this case you can use the newest features. But be careful, they are probably not fully tested.

**Comment by drissamri** [comment]
Alright @MathiasTim, makes sense, didn't know it was a new feature in the generator. Keep up the good work though!

**Comment by MathiasTim** [comment]
@gruppjo maybe we should stop putting features into master, when they are not released? What do you think? I kinda understand @drissamri, it is confusing, if you go to a repo and it tells you It has this feature, you do an npm install and it don't.

**Comment by drissamri** [comment]
That, and also the fact the [sample app](https://github.com/mwaylabs/generator-m-demo) also has the new features.

**Comment by gruppjo** [comment]
@MathiasTim, @drissamri. You are right, this is confusing. I've been thinking about this issue as well recently... Maybe it's time to build up a master/dev branch on both repositories after the next release!

Thanks for your feedback!

**Comment by gruppjo** [comment]
Will do so as of today.
