### ISSUE TITLE
Sqlite plugin

### ISSUE THREAD

**Issue by num3r06** [mwaylabs/generator-m#236]
Hi, i try to use Sqlite plugin with this generator but when i build app with this app.js

```js
'use strict';
var db = null;
angular.module('Mionic', [
  // load your modules here
  'main' // starting with the main module
])
.constant('ApiEndPoint', {
  url: 'http://localhost:8088/laravel_api/public/api/'})

.run(function ($ionicPlatform, $cordovaSQLite) {
  $ionicPlatform.ready(function () {
    if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if (window.StatusBar) {
      StatusBar.styleDefault();
    }
    window.plugins.sqlDB.copy('my.db', function () {
    db = $cordovaSQLite.openDB('my.db');
  }, function (error) {
    console.error('There was an error copying the database: ' + error);
    db = $cordovaSQLite.openDB('my.db');
  });
  });
});
```

gulp return error:
window in not defined.
Where is the error
Thx

**Comment by gruppjo** [comment]
Hi @num3r06, I put your code in a code block to make it easier on the eyes ;)
In angular it's better to inject the `$window` service rather than using the global window object.

For more information see here. https://docs.angularjs.org/api/ng/service/$window

In this case we configured jshint in the generator to help avoid the usage of `window` and rather use `$window` instead.

**Comment by num3r06** [comment]
Thx for reply

**Comment by gruppjo** [comment]
Does that solve your issue?

**Comment by num3r06** [comment]
I'm testing but the solution is far away... :(
The big problem is code debug's outside of browser. I doesn't undesrstand how use my Sqlite DB (seems to be deleted after build).
The goal of my application is read from external api (laravel/mysql) and populated SQlite db for offline use. I'm using your generator for create app and a lot of code for integrate SQlite plugin. I need to use SQLite because other localStorage has to many limit
Thx for interesting

**Comment by gruppjo** [comment]
But the original problem with `window` being undefined is now clear, right? - Because then I'll close this issue.

On a side note: We used https://github.com/angular-pouchdb/angular-pouchdb for similar purposes in a couple of our projects. It might be worth a look.
