### ISSUE TITLE
Consider node-sass or lib-sass as a replacement for ruby sass

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#3]
Consider node-sass or lib-sass as a replacement for ruby sass thus get rid of the ruby/sass dependency

https://github.com/dlmanning/gulp-sass
https://github.com/sass/node-sass (gulp-sass may not work with plumber)
https://github.com/sass/libsass 
https://github.com/medialize/sass.js (emscripten, so no libsass installation is needed, cumbersome on windows)

**Comment by gruppjo** [comment]
Here are my findings so far:

## different projects
[Libass](https://github.com/sass/libsass) is just the library to compile sass natively in C to css. To actually run it, you need a wrapper to execute it. This can be done using [sassc](https://github.com/sass/sassc) a command line driver (install via brew `brew install sassc`) or a [language wrapper](https://github.com/sass/libsass/wiki/Implementations) like [node-sass](https://github.com/sass/node-sass), [sass.js](https://github.com/medialize/sass.js) is basically the same thing just for the use in the browser.

## sassc
At first I ran sass using and it was incredibly fast. From the command line it felt pretty much instant (even when compiling the whole ionic sass).

## gulp-sass
I used [gulp-sass](https://github.com/dlmanning/gulp-sass) to run the whole thing with gulp on mac & windows (using virtual box and the window 7 with ie10 from modern.ie http://dev.modern.ie/tools/vms/). Despite the [node-sass installation notes](https://github.com/sass/node-sass#install) which suggest that it's only a binding and you need to install libsass for yourself, this is not the case. Even on windows where it state that visual studio is required on windows, gulp-sass installed and ran flawlessly without it. I assume they're providing precompiled binaries.

The results?
### speed
Well... See for yourself. First ist ruby-sass, second is gulp-sass. Quite the opposite of what I was expecting.
![screen shot 2015-05-22 at 12 56 36](https://cloud.githubusercontent.com/assets/1370779/7769679/4f375cd2-0086-11e5-9ffb-e0501e8f43ab.png)

### sourcemaps, autoprefixer, error handling
gulp-sass works without any problems, with sourcemaps and autoprefixer. Error-handling is not satisfying though, because it doesn't work with plumber effectively halting the gulp watch task when you have any errors, even if you catch them. 
![screen shot 2015-05-22 at 13 30 33](https://cloud.githubusercontent.com/assets/1370779/7769718/bfdce83a-0086-11e5-9dd9-7367542db702.png)

If you want, you can try for yourself cloning this branch (https://github.com/mwaylabs/generator-m/tree/lib-sass) of the generator and `npm link` it and then run `yo m --skip-prompts'.

**Comment by gruppjo** [comment]
reserach plumber use

**Comment by gruppjo** [comment]
Some issues I found regarding the slow compilation speed with node-sass:

- gulp-sass https://github.com/dlmanning/gulp-sass/issues/258
- lib-sass https://github.com/sass/libsass/issues/1205
- node-sass https://github.com/sass/node-sass/issues/970

**Comment by gruppjo** [comment]
plumber use:

- https://github.com/dlmanning/gulp-sass/issues/44
- https://github.com/dlmanning/gulp-sass/issues/90

Improvement suggestion for implementation: https://github.com/dlmanning/gulp-sass/issues/90#issuecomment-112052541

**Comment by gruppjo** [comment]
~~name `main.scss` `module.scss`~~

**Comment by Telemakhos** [comment]
Compiling SASS is really slow compared to other projects like Swiip's generator-gulp-angular, I'd say it's almost unusable... The current defaults for the generator seems like don't fix the issue. If you managed to fix this could you point us to the solution? Maybe downgrading node-sass/libsass?

**Comment by gruppjo** [comment]
Hi @Telemakhos, thanks for your feedback. Could you please provider further information on your issue:

- which OS are you running (Mac OSX, Windows 7/8, ...)
- which version of node are you running `node -v`
- what kind of drawbacks are you experiencing?
  - note that a compile time of 2 to 6 seconds is common (more on windows), when the whole ionic scss is compiled in every step (which the generator does because we like to enhance the ionic sass for our projects).

If this problem persists, please open a new issue or refer to this one, if the speed of your compilation is within the above tolerance: 
https://github.com/mwaylabs/generator-m/issues/212

**Comment by Telemakhos** [comment]
> which OS are you running

OSX Yosemite 10.4.4

> which version of node are you running

v0.12.4

> what kind of drawbacks are you experiencing?

As you mention, the gulp scss task takes 6 secs to compile. We have several projects with gulp + scss with node-sass with much bigger stylesheet codebases and all compile times are 0-2 secs (what we understand as *acceptable*). So we thought something was wrong with the boilerplate defaults...

I will try to include the precompiled ionic css as you say, or maybe tweak the gulp tasks...

**Comment by gruppjo** [comment]
Hi @Telemakhos, sorry for the late reply. I fell sick and it took me a while to recover.
I think it would be good idea to be able to choose whether you want precompiled ionic css or the sass version. This shouldn't be a major change so I think we might implement it soon.
See https://github.com/mwaylabs/generator-m/issues/212.
If you find out anything about the overall performance of gulp-sass/node-sass or possible tweaks for the gulp tasks, please let us know. We've been doing some digging around on these topics as well. I can't say with overwhelming success so far...

**Comment by Telemakhos** [comment]
Hi @gruppjo, you're proposal is a nice fix in the mean time, but it's a major decrease in performance that should be addressed in its origin. We've pinpointed the source of the problem in the node-sass module. 

Until the issue is (hopefully) resolved, some of us are downgrading. Consider using gulp-sass 1.3.3 (node-sass 2.1.1) in the mean time. Ionic Framework guys are still using node-sass 2.x in their official boilerplates and the framework users are doing just fine.

**Comment by gruppjo** [comment]
@Telemakhos, the master version of the generator now supports to choose the precompiled css of ionic as of 38ae043a7da86891fe02f1f5d8bf870f24a8933c.
Additionally we prepared a guide how to switch from one to the other (gulp tasks, etc...) in the docs, see https://github.com/mwaylabs/generator-m/blob/master/docs/guides/ionic_css_or_sass.md.
