### ISSUE TITLE
Add more sub-generators

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#32]
Project structure and modularization needs to be defined first: #31 

improvements:
* named functions for sub-generators
* multi-module project structure/settings/generators (ask for module?)

more generators:
* template
* directive
* filter
* constant
* find more: https://github.com/yeoman/generator-angular

out of scope: 
* create routes

gulp
- adjust paths in generator gulpfile
- adjust generated gulpfiles (necessary?)

readme
- update!

**Comment by LunarDevelopment** [comment]
Can I ask why theres now create route (state) sub gen? 

Or if theres plans to make one?

**Comment by gruppjo** [comment]
Hi @LunarDevelopment, the main reason we decided not to create one is because it would require to parse and manipulate the `'module'.js` files and this can be quite cumbersome and error-prone especially when there's a lot going on in this file. For every other sub-generator so far it suffices to create and inject new files. So reason # 1: simplicity, testability.

Another reason is that we don't want to build an app-build or something of that fashion. Working with the generator should *not* keep you from learning the technologies that you use (in this case the ui-router), it much rather should gently guide you towards learning and comprehending on your own. Thus enabling to keep your mind focused on the project's unique requirements while taking all the repetitive and time-consuming setup and configuration tasks off your shoulders. 

Setting up a state depends on many factors: are you using different ui-views, is it an abstract one, what kind of templates are you using (inline, or template files), etc... etc... In our opinion there's not much boilerplate much rather a lot of logic that depends on your project and thus, the code needed to reproduce that behavior is already the most efficient and comprehensive way to achieve that.

**Comment by LunarDevelopment** [comment]
All very good reasons, thanks for taking the time!

**Comment by gruppjo** [comment]
You're welcome! We know our reasoning isn't bullet-proof so we take any chance to validate it, so thank *you* for bringing it up.
