### ISSUE TITLE
gulp: source maps

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#38]
for better debugging.

#3 Needs to be solved first, when considering source maps for gulp-ruby-sass

- gulp-ruby-sass - https://github.com/sindresorhus/gulp-ruby-sass
  - sourcemaps? - https://github.com/sindresorhus/gulp-

**Comment by MathiasTim** [comment]
+1

**Comment by gruppjo** [comment]
Couldn't figure out what was going on for almost forever. Finally found this: https://github.com/superbiche/gulp/blob/master/docs/recipes/sourcemaps-with-sass-and-autoprefixer.md

**Comment by MathiasTim** [comment]
Sorry, but still don't seem to work for imported files (```_filename.scss```).
<img width="738" alt="screen shot 2015-09-05 at 13 39 07" src="https://cloud.githubusercontent.com/assets/1793379/9699072/c0e24720-53d3-11e5-9b90-b9e6df2b7748.png">
<img width="266" alt="screen shot 2015-09-05 at 13 39 00" src="https://cloud.githubusercontent.com/assets/1793379/9699074/c4b9cbe8-53d3-11e5-835f-fc4c41d1f112.png">
<img width="249" alt="screen shot 2015-09-05 at 13 39 13" src="https://cloud.githubusercontent.com/assets/1793379/9699075/c72f44c0-53d3-11e5-8b36-21a42c100674.png">

**Comment by gruppjo** [comment]
new issue #243
