### ISSUE TITLE
Assemble utils module

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#43]
Collect best-practices in util module that can be reused in other projects.
Ideas:
- delimiter filter
  - dash
  - pipe
- localForage/localStorage sevice with encryption for userData etc...
- error logging (api/http/crittercism)
- metering (how many requests per day, payload, using which functions, ...?)

**Comment by MathiasTim** [comment]
Basically a good idea. But I think this will take much maintaining effort. I would prefer a FAQ/recipe solution. @gruppjo what do you think?

**Comment by gruppjo** [comment]
yes, old idea.
