### ISSUE TITLE
Adjustments to generator prompts: plugins, bower, ...

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#64]
When running the generator provide all ngCordova plugins
- is there an API to check, or do we have to keep it up to date manually?
- do we want all plugins? - no there's a lot.

**Comment by MathiasTim** [comment]
If we cannot crawl ngCordova, I would change the current plugins to some others/more.
E.g. the toast plugin is in my opinion not really used often.
So we should discuss this for the next version, to make this even more  easy for beginners.

**Comment by gruppjo** [comment]
ng-cordova
- statusbar
- device
- splashscreen
- network
- dialogs
- inappbrowser
