### ISSUE TITLE
make ionic alternatives available

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#74]
- angular material - https://github.com/angular/material
- mobile angular ui - http://mobileangularui.com/
   - ng route / ui-router support
   - scaffolding
   - ios header distance (config.xml)
- ratchet
- touchdown?

**Comment by DrMabuse23** [comment]
There is a startup to integrate material in ionic http://ionicmaterial.com/ but when i look at the jobs offer on ionic it looks like ionic want to integrate angular-material

**Comment by MathiasTim** [comment]
I don't think this discussion is relevant anymore. I think when we want to support another ui framework we have to change a lot more, than just changing the bower component. (templates, etc.)
It will be also difficult if we want better starting templates for newbies.

**Comment by gruppjo** [comment]
Yes!
