### ISSUE TITLE
copy static files to www folder on build

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m#78]
sometimes it's necessary to copy additional static files to the www folder
* changelogs
* readmes

provide a hook (maybe a separate folder) that contain those files

**Comment by MathiasTim** [comment]
I think we do this already. Everything in assets will be copied to the www folder, so I'll close this issue.

**Comment by fmendoza** [comment]
In my case I have a json file in the root of my app folder, but this file isn't being copied to the root of www folder. Any help?

**Comment by gruppjo** [comment]
Does it need to be in the app folder? You could move it to `assets`. If that doesn't suffice you can write your own gulp task to do so and add it to the build tasks. https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/gulp/building.js#L16
